### PR TITLE
Refactor build process

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by kdeldycke** [comment]
Holy cow. That's what I call a serious PR! 😄 

Are you waiting for any feedback? Or is that still a work in progress?

**Comment by sieben** [comment]
@kdeldycke My goal is to have a repo that can be built as a stand-alone. It's still a work in progress. I will be sure to mention you once it's ready for review :)

**Comment by iManu** [comment]
@sieben we have to see together about the install process, like grunt use cases and more. There is so many deprecated stuff and warnings, conflicts etc. Installation is terrific :/

**Comment by sieben** [comment]
I'm all in favor of trashing it and starting clean from https://github.com/swagger-api/swagger-ui or https://github.com/Rebilly/ReDoc

**Pull request closed without merging**
